-- ============================================================================
-- Venuxiio commission site — Supabase schema + permissions + seed data
-- Paste into: Supabase dashboard → SQL Editor → New query → Run (once)
-- ============================================================================

-- --------------------------------------------------------------------------
-- Tables
-- --------------------------------------------------------------------------

create table if not exists public.services (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null default 'full_render' check (category in ('full_render', 'sketch')),
    base_price int not null default 0,
    extra_char_price int not null default 0,
    description text not null default '',
    image text not null default '',
    active boolean not null default true,
    sort int not null default 0
);

create table if not exists public.commissions (
    id bigint generated by default as identity primary key,
    client text not null default '',
    contact text not null default '',
    service text not null default '',
    details text not null default '',
    refs text not null default '',
    estimate numeric,
    status text not null default 'request'
        check (status in ('request', 'waiting', 'in_progress', 'finished')),
    paid boolean not null default false,
    sort_order int,
    created_at timestamptz not null default now()
);

create table if not exists public.settings (
    id int primary key default 1 check (id = 1),   -- single row
    comms_open boolean not null default false,
    reopen_date date,
    max_slots int not null default 8,
    art_trades_open boolean not null default false,
    requests_open boolean not null default false,
    announcement text not null default ''
);

-- --------------------------------------------------------------------------
-- Public (anon) view of commissions: hides pending requests entirely and
-- strips contact / details / refs columns so client info never reaches a
-- browser via the anon key. Admin (service_role) reads the base table.
-- --------------------------------------------------------------------------

create or replace view public.commissions_public as
select id, client, service, estimate, status, paid, sort_order, created_at
from public.commissions
where status <> 'request';

grant select on public.commissions_public to anon, authenticated;

-- --------------------------------------------------------------------------
-- Row Level Security — this is the whole permission model.
-- The anon key (embedded in the public site) is limited by the DATABASE:
--   services   : read active rows
--   commissions: read the public view (no request rows, no contact columns);
--                insert ONLY rows with status = 'request' (and no way to
--                mark paid, impersonate update/delete — those are simply
--                not granted)
--   settings   : read
-- The service_role key bypasses RLS entirely (admin board).
-- --------------------------------------------------------------------------

alter table public.services enable row level security;
alter table public.commissions enable row level security;
alter table public.settings enable row level security;

-- services: public reads active services
drop policy if exists "services_public_read" on public.services;
create policy "services_public_read"
    on public.services for select
    to anon, authenticated
    using (active = true);

-- commissions: public inserts request rows only —
-- forced by the check constraint + this insert-only policy
drop policy if exists "commissions_public_insert_request" on public.commissions;
create policy "commissions_public_insert_request"
    on public.commissions for insert
    to anon, authenticated
    with check (
        status = 'request'
        and paid = false
        and coalesce(client, '')  <> ''
        and coalesce(service, '') <> ''
    );

-- settings: public reads the single settings row
drop policy if exists "settings_public_read" on public.settings;
create policy "settings_public_read"
    on public.settings for select
    to anon, authenticated
    using (true);

-- NOTE: commissions has NO anon select policy on the base table — anon reads
-- go through the commissions_public view above. No update/delete policies
-- exist for anon anywhere: by default RLS denies everything not granted.

-- --------------------------------------------------------------------------
-- Seed data — current prices + queue (September 2026)
-- --------------------------------------------------------------------------

insert into public.services (name, category, base_price, extra_char_price, description, image, active, sort) values
    ('Bust',            'full_render', 40,  35, '', 'assets/images/examples/bust/bust.webp', true, 1),
    ('Halfbody',        'full_render', 50,  40, '', 'assets/images/examples/halfbody/halfbody.webp', true, 2),
    ('Knee up',         'full_render', 70,  60, '', 'assets/images/examples/kneeup/kneeup.webp', true, 3),
    ('Fullbody',        'full_render', 90,  70, '', 'assets/images/examples/fullbody/fullbody.webp', true, 4),
    ('Chibi',           'full_render', 40,  35, '', 'assets/images/examples/chibi/chibi.webp', true, 5),
    ('Custom',          'full_render', 100, 0,  'Fullbody by default. Final price varies with character complexity; includes a moodboard plus an assigned animal.', 'assets/images/examples/custom/custom.webp', true, 6),
    ('Reference sheet', 'full_render', 200, 0,  'Check the example image in the gallery.', 'assets/images/examples/refsheet/Illustration15.webp', true, 7),
    ('Sketch Bust',     'sketch', 15, 0, '', 'assets/images/examples/bust/bust2.webp', true, 8),
    ('Sketch Halfbody', 'sketch', 24, 0, '', 'assets/images/examples/halfbody/halfbody2.webp', true, 9),
    ('Sketch Knee up',  'sketch', 30, 0, '', 'assets/images/examples/kneeup/kneeup2.webp', true, 10),
    ('Sketch Fullbody', 'sketch', 40, 0, '', 'assets/images/examples/fullbody/fullbody1.webp', true, 11),
    ('Sketch Chibi',    'sketch', 15, 0, '', 'assets/images/examples/chibi/chibi1.webp', true, 12)
on conflict do nothing;

-- queue: waiting list
insert into public.commissions (client, service, status, paid, sort_order) values
    ('da_glooba',   'Halfbody',          'waiting', false, 1),
    ('thealvinxu',  'two knees up',      'waiting', false, 2),
    ('lexlul09',    'halfbody unshaded', 'waiting', false, 3),
    ('Seong_strz',  'Fullbody',          'waiting', false, 4),
    ('cyborne_exe', 'Custom',            'waiting', false, 5);

-- queue: finished history
insert into public.commissions (client, service, status, paid, sort_order) values
    ('eddytails',         'fullbody + bg',         'finished', true, 1),
    ('da.veed05',         '2 Knee ups',            'finished', true, 2),
    ('Ashttro',           'Sketch fullbody',       'finished', true, 3),
    ('H.z.a3_',           'Two fullbodies',        'finished', true, 4),
    ('Sif_3905',          'Halfbody',              'finished', true, 5),
    ('simp4lava',         'Halfbody',              'finished', true, 6),
    ('Landspeeda',        '2 halfbodies',          'finished', true, 7),
    ('Albino_Trash_Panda','Knee up',               'finished', true, 8),
    ('H.z.a3_',           'Sketch fullbody',       'finished', true, 9),
    ('Jesusrocha',        'Halfbody + background', 'finished', true, 10),
    ('theo_frv1',         'Fullbody+background',   'finished', true, 11),
    ('nexystuff',         '2 halfbodies',          'finished', true, 12);

-- settings: single row (commissions currently closed)
insert into public.settings (id, comms_open, reopen_date, max_slots, art_trades_open, requests_open)
values (1, false, null, 8, false, false)
on conflict (id) do nothing;
