-- ============================================================================
-- Venuxiio commission site — Supabase schema + permissions
-- Paste into: Supabase dashboard → SQL Editor → New query → Run (once)
-- The database stores COMMISSION REQUESTS ONLY. Services, prices and the
-- open/closed settings live in commissions.js and are hand-edited there —
-- they are deliberately not tables.
-- NOTE (Sep 2026): existing installs should run migrations/
-- 2026-09-11-drop-settings-services-tables.sql to drop the now-unused
-- services + settings tables, and migrations/2026-09-11-reference-images.sql
-- for the attachments column + the commission-refs storage bucket.

-- --------------------------------------------------------------------------
-- Tables
-- --------------------------------------------------------------------------

create table if not exists public.commissions (
    id bigint generated by default as identity primary key,
    client text not null default '',
    contact text not null default '',
    service text not null default '',
    details text not null default '',
    refs text not null default '',
    options jsonb not null default '{}'::jsonb,
    attachments jsonb not null default '[]'::jsonb,
    estimate numeric,
    status text not null default 'request'
        check (status in ('request', 'waiting', 'in_progress', 'finished')),
    paid boolean not null default false,
    sort_order int,
    created_at timestamptz not null default now()
);

-- --------------------------------------------------------------------------
-- Row Level Security — this is the whole permission model.
-- The anon key (embedded in the public site) is limited by the DATABASE:
--   commissions: NO read access at all (only the admin board reads
--                commissions); insert ONLY rows with status = 'request'
--                (and no way to mark paid, impersonate update/delete —
--                those are simply not granted)
-- The service_role key bypasses RLS entirely (admin board).
-- --------------------------------------------------------------------------

alter table public.commissions enable row level security;

-- Commissions is the only table: anon gets INSERT and nothing else.
revoke all on public.commissions from anon, authenticated;
grant insert on public.commissions to anon, authenticated;

-- commissions: public inserts request rows only —
-- forced by the check constraint + this insert-only policy
drop policy if exists "commissions_public_insert_request" on public.commissions;
create policy "commissions_public_insert_request"
    on public.commissions for insert
    to anon, authenticated
    with check (
        status = 'request'
        and paid = false
        and coalesce(client, '')  <> ''
        and coalesce(service, '') <> ''
    );

-- NOTE: commissions has NO anon select policy — anon cannot read commission
-- rows at all (insert-only for requests). No update/delete policies exist
-- for anon anywhere: by default RLS denies everything not granted.

-- No seed rows: the queue starts empty and real rows arrive through the
-- request form / admin board.
