-- ============================================================================
-- Venuxiio commission site — Supabase schema + permissions + seed data
-- Paste into: Supabase dashboard → SQL Editor → New query → Run (once)
-- NOTE (Sep 2026): the public queue was removed — anon no longer reads
-- commissions at all. Existing installs should run migrations/
-- 2026-09-08-drop-public-queue.sql. The view + queue seeds below are kept
-- out; fresh installs match the current site.

-- --------------------------------------------------------------------------
-- Tables
-- --------------------------------------------------------------------------

create table if not exists public.services (
    id bigint generated by default as identity primary key,
    name text not null,
    base_price int not null default 0,
    extra_char_price int not null default 0,
    description text not null default '',
    image text not null default '',
    active boolean not null default true,
    sort int not null default 0
);

create table if not exists public.commissions (
    id bigint generated by default as identity primary key,
    client text not null default '',
    contact text not null default '',
    service text not null default '',
    details text not null default '',
    refs text not null default '',
    options jsonb not null default '{}'::jsonb,
    estimate numeric,
    status text not null default 'request'
        check (status in ('request', 'waiting', 'in_progress', 'finished')),
    paid boolean not null default false,
    sort_order int,
    created_at timestamptz not null default now()
);

create table if not exists public.settings (
    id int primary key default 1 check (id = 1),   -- single row
    comms_open boolean not null default false,
    reopen_date date,
    max_slots int not null default 8,
    announcement text not null default ''
);

-- --------------------------------------------------------------------------
-- Row Level Security — this is the whole permission model.
-- The anon key (embedded in the public site) is limited by the DATABASE:
--   services   : read active rows
--   commissions: NO read access at all (the public queue is gone — only the
--                admin board reads commissions); insert ONLY rows with
--                status = 'request' (and no way to mark paid, impersonate
--                update/delete — those are simply not granted)
--   settings   : read
-- The service_role key bypasses RLS entirely (admin board).
-- --------------------------------------------------------------------------

alter table public.services enable row level security;
alter table public.commissions enable row level security;
alter table public.settings enable row level security;

-- services: public reads active services
drop policy if exists "services_public_read" on public.services;
create policy "services_public_read"
    on public.services for select
    to anon, authenticated
    using (active = true);

-- commissions: public inserts request rows only —
-- forced by the check constraint + this insert-only policy
drop policy if exists "commissions_public_insert_request" on public.commissions;
create policy "commissions_public_insert_request"
    on public.commissions for insert
    to anon, authenticated
    with check (
        status = 'request'
        and paid = false
        and coalesce(client, '')  <> ''
        and coalesce(service, '') <> ''
    );

-- settings: public reads the single settings row
drop policy if exists "settings_public_read" on public.settings;
create policy "settings_public_read"
    on public.settings for select
    to anon, authenticated
    using (true);

-- NOTE: commissions has NO anon select policy — anon cannot read commission
-- rows at all (insert-only for requests). No update/delete policies exist
-- for anon anywhere: by default RLS denies everything not granted.

-- --------------------------------------------------------------------------
-- Seed data — current prices (September 2026)
-- --------------------------------------------------------------------------

insert into public.services (name, base_price, extra_char_price, description, image, active, sort) values
    ('Bust',            40,  35, '', 'assets/images/examples/bust/bust.webp', true, 1),
    ('Halfbody',        50,  40, '', 'assets/images/examples/halfbody/halfbody.webp', true, 2),
    ('Knee up',         70,  60, '', 'assets/images/examples/kneeup/kneeup.webp', true, 3),
    ('Fullbody',        90,  70, '', 'assets/images/examples/fullbody/fullbody.webp', true, 4),
    ('Chibi',           40,  35, '', 'assets/images/examples/chibi/chibi.webp', true, 5),
    ('Custom',          100, 0,  'Fullbody by default. Final price varies with character complexity; includes a moodboard plus an assigned animal.', 'assets/images/examples/custom/custom.webp', true, 6),
    ('Reference sheet', 200, 0,  'Check the example image in the gallery.', 'assets/images/examples/refsheet/Illustration15.webp', true, 7)
on conflict do nothing;

-- No commission seed rows: the queue is admin-only now, so it starts empty
-- and real rows arrive through the request form / admin board.

-- settings: single row (commissions currently closed)
insert into public.settings (id, comms_open, reopen_date, max_slots)
values (1, false, null, 8)
on conflict (id) do nothing;
